name: Build and Deploy to Azure App Service
 
on:
  push:
    branches:
      - main   # triggers the workflow when you push to main branch
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
 
      - name: Install dependencies
        run: npm install
 
      - name: Build (optional)
        run: npm run build --if-present
 
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: destanapp   # 🟢 Replace with your App Service name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
