name: Build and Deploy to Azure App Service
 
on:

  push:

    branches:

      - main
 
jobs:

  build-and-deploy:

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout code

        uses: actions/checkout@v3
 
      - name: Setup Node.js

        uses: actions/setup-node@v3

        with:

          node-version: '20.x'
 
      - name: Install dependencies

        run: npm install
 
      - name: Build (optional)

        run: npm run build --if-present
 
      # 🔹 Login to Azure using Service Principal

      - name: Azure Login

        uses: azure/login@v1

        with:

          creds: ${{ secrets.AZURE_CREDENTIALS }}
 
      # 🔹 Deploy to Azure Web App

      - name: Deploy to Azure Web App

        uses: azure/webapps-deploy@v2

        with:

          app-name: destanapp   # Replace with your App Service name

          package: .

 
